language: go
go_import_path: github.com/jarcoal/httpmock

sudo: false

matrix:
  include:
    - go: 1.7.x
    - go: 1.8.x
    - go: 1.9.x
    - go: 1.10.x
    - go: 1.11.x
    - go: 1.12.x
    - go: 1.13.x
    - go: 1.14.x
    - go: 1.15.x
      env:
        - USE_LINTER=1
        - GO_TEST_OPTS="-covermode=atomic -coverprofile=coverage.out"
      install:
        - wget -O - -q https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.30.0
      after_success:
        - go get github.com/mattn/goveralls
        - goveralls -coverprofile=coverage.out -service=travis-ci
    - go: master
  allow_failures:
    - go: master
  fast_finish: true

script:
  - export GORACE="halt_on_error=1"
  - go test -race $GO_TEST_OPTS ./...
  - >
    if [ "$USE_LINTER" = 1 ]; then
      golangci-lint run --max-issues-per-linter 0 \
                        --max-same-issues 0 \
                        -E exportloopref \
                        -E gocritic \
                        -E godot \
                        -E goimports \
                        -E golint \
                        -E maligned \
                        -E misspell \
                        -E prealloc \
                        -E unconvert \
                        -E whitespace \
                        ./...;
    fi

notifications:
  email: false
